#include<stdio.h>
#include<conio.h>
void main()
{
int ch;
clrscr();
printf("\n Elements of the periodic table");
printf("\n The elements of the periodic table are mainly categorized into following types");
printf("\n---------------------------------------------------------------------------------");
printf("\n 1.Alkali Metals");
printf("\n 2.Alkaline Earth");
printf("\n 3.Transition Metals");
printf("\n 4.Basic Metals");
printf("\n 5.Metalloid");
printf("\n 6.Non-metals");
printf("\n 7.Halogen");
printf("\n 8.Noble gas");
printf("\n 9.Lanthanides");
printf("\n10.Actinides");
scanf("%d",&ch);
switch(ch)
{
case 1 : printf("\n The different elements of Alkali metals are:" );
	 printf("\n-------------------------------------------------");
	 printf("\n Element 1 \nSymbolic name:- Li");
	 printf("\n Full form :-Lithium");
	 printf("\n Atomic number:-3");
	 printf("\n Atomic mass number:-6.941");
	 printf("\n---------------------------------");
	 printf("\n Element 2 \nSymbolic name:- Na");
	 printf("\n Full form :-Sodium");
	 printf("\n Atomic number:-11");
	 printf("\n Atomic mass number:- 22.990");
	 printf("\n---------------------------------");
	 system("pause");
	 printf("\n Element 3 \nSymbolic name:- K");
	 printf("\n Full form :-Potassium");
	 printf("\n Atomic number:-19");
	 printf("\n Atomic mass number:- 39.908");
	 printf("\n---------------------------------");
	 printf("\n Element 4 \nSymbolic name:- Rb");
	 printf("\n Full form :-Rubidium");
	 printf("\n Atomic number:- 37");
	 printf("\n Atomic mass number:- 84.468");
	 printf("\n---------------------------------");
	 printf("\n Element 5 \nSymbolic name:- Cs");
	 printf("\n Full form :-Cesium");
	 printf("\n Atomic number:- 55");
	 printf("\n Atomic mass number:- 132.905");
	 printf("\n---------------------------------");
	 printf("\n Element 6 \nSymbolic name:- Fr");
	 printf("\n Full form :-Francium");
	 printf("\n Atomic number:- 87");
	 printf("\n Atomic mass number:- 23.020");
	 printf("\n---------------------------------");
	 break;

case 2 : printf("\n The different elements of Alkaline Earth metals are:" );
	 printf("\n-------------------------------------------------------");
	 printf("\n Element 1 \nSymbolic name:- Be");
	 printf("\n Full form :-Beryllium");
	 printf("\n Atomic number:- 4");
	 printf("\n Atomic mass number:- 9.012");
	 printf("\n---------------------------------");
	 printf("\n Element 2 \nSymbolic name:- Mg");
	 printf("\n Full form :-Magnesium");
	 printf("\n Atomic number:-12");
	 printf("\n Atomic mass number:- 24.305");
	 printf("\n---------------------------------");
	 printf("\n Element 3 \nSymbolic name:- Ca");
	 printf("\n Full form :-Calcium");
	 printf("\n Atomic number:-20");
	 printf("\n Atomic mass number:- 40.078");
	 printf("\n---------------------------------");
	 printf("\n Element 4 \nSymbolic name:- Sr");
	 printf("\n Full form :-Strantium");
	 printf("\n Atomic number:- 38");
	 printf("\n Atomic mass number:- 87.62");
	 printf("\n---------------------------------");
	 system("pause");
	 printf("\n Element 5 \nSymbolic name:- Ba");
	 printf("\n Full form :-Barium");
	 printf("\n Atomic number:- 56");
	 printf("\n Atomic mass number:- 137.328");
	 printf("\n---------------------------------");
	 printf("\n Element 6 \nSymbolic name:- Ra");
	 printf("\n Full form :-Radium");
	 printf("\n Atomic number:- 88");
	 printf("\n Atomic mass number:- 226.025");
	 printf("\n---------------------------------");
	 break;
case 3 : printf("\n The different elements of Transition metals are:" );
	 printf("\n-------------------------------------------------------");
	 printf("\n Element 1 \nSymbolic name:- Sc");
	 printf("\n Full form :-Scandium");
	 printf("\n Atomic number:- 21");
	 printf("\n Atomic mass number:- 44.956");
	 printf("\n---------------------------------");
	 printf("\n Element 2 \nSymbolic name:- Ti");
	 printf("\n Full form :-Titanium");
	 printf("\n Atomic number:-22");
	 printf("\n Atomic mass number:- 47.88");
	 printf("\n---------------------------------");
	 system("pause");
	 printf("\n Element 3 \nSymbolic name:- V");
	 printf("\n Full form :-Vanadium");
	 printf("\n Atomic number:-23");
	 printf("\n Atomic mass number:- 50.942");
	 printf("\n---------------------------------");
	 printf("\n Element 4 \nSymbolic name:- Cr");
	 printf("\n Full form :-Chromium");
	 printf("\n Atomic number:- 24");
	 printf("\n Atomic mass number:- 51.996");
	 printf("\n---------------------------------");
	 printf("\n Element 5 \nSymbolic name:- Mn");
	 printf("\n Full form :-Manganese");
	 printf("\n Atomic number:- 25");
	 printf("\n Atomic mass number:- 54.938");
	 printf("\n---------------------------------");
	 printf("\n Element 6 \nSymbolic name:- Fe");
	 printf("\n Full form :-Iron");
	 printf("\n Atomic number:- 26");
	 printf("\n Atomic mass number:- 55.845");
	 printf("\n---------------------------------");
	 system("pause");
	 printf("\n Element 7 \nSymbolic name:- Co");
	 printf("\n Full form :-Cobalt");
	 printf("\n Atomic number:- 27");
	 printf("\n Atomic mass number:- 58.993");
	 printf("\n---------------------------------");
	 printf("\n Element 8 \nSymbolic name:- Ni");
	 printf("\n Full form :-Nickel");
	 printf("\n Atomic number:-28");
	 printf("\n Atomic mass number:- 58.693");
	 printf("\n---------------------------------");
	 printf("\n Element 9 \nSymbolic name:- Cu");
	 printf("\n Full form :-Copper");
	 printf("\n Atomic number:-29");
	 printf("\n Atomic mass number:- 63.546");
	 printf("\n---------------------------------");
	 printf("\n Element 10 \nSymbolic name:- Zn");
	 printf("\n Full form :-Zinc");
	 printf("\n Atomic number:- 30");
	 printf("\n Atomic mass number:- 65.38");
	 printf("\n---------------------------------");
	 system("pause");
	 printf("\n Element 11 \nSymbolic name:- Y");
	 printf("\n Full form :-Yttrium");
	 printf("\n Atomic number:- 39");
	 printf("\n Atomic mass number:- 88.906");
	 printf("\n---------------------------------");
	 printf("\n Element 12 \nSymbolic name:- Zr");
	 printf("\n Full form :-Zirconium");
	 printf("\n Atomic number:-40");
	 printf("\n Atomic mass number:- 91.224");
	 printf("\n---------------------------------");
	 printf("\n Element 13 \nSymbolic name:- Nb");
	 printf("\n Full form :-Niobium");
	 printf("\n Atomic number:-41");
	 printf("\n Atomic mass number:- 92.906");
	 printf("\n---------------------------------");
	 printf("\n Element 14 \nSymbolic name:- Mo");
	 printf("\n Full form :-Molybdenum");
	 printf("\n Atomic number:- 42");
	 printf("\n Atomic mass number:- 95.95");
	 printf("\n---------------------------------");
	 system("pause");
	 printf("\n Element 15 \nSymbolic name:- Tc");
	 printf("\n Full form :-Technetium");
	 printf("\n Atomic number:- 43");
	 printf("\n Atomic mass number:- 98.907");
	 printf("\n---------------------------------");
	 printf("\n Element 16 \nSymbolic name:- Ru");
	 printf("\n Full form :-Ruthenium");
	 printf("\n Atomic number:- 44");
	 printf("\n Atomic mass number:- 101.07");
	 printf("\n---------------------------------");
	 printf("\n Element 17 \nSymbolic name:- Rh");
	 printf("\n Full form :-Rhodium");
	 printf("\n Atomic number:- 45");
	 printf("\n Atomic mass number:- 102.906");
	 printf("\n---------------------------------");
	 printf("\n Element 18 \nSymbolic name:- Pd");
	 printf("\n Full form :-Palladium");
	 printf("\n Atomic number:- 46");
	 printf("\n Atomic mass number:- 106.42");
	 printf("\n---------------------------------");
	 system("pause");
	 printf("\n Element 19 \nSymbolic name:- Ag");
	 printf("\n Full form :-Silver");
	 printf("\n Atomic number:-47");
	 printf("\n Atomic mass number:- 107.868");
	 printf("\n---------------------------------");
	 printf("\n Element 20 \nSymbolic name:- Cd");
	 printf("\n Full form :-Cadmium");
	 printf("\n Atomic number:-48");
	 printf("\n Atomic mass number:- 112.414");
	 printf("\n---------------------------------");
	 printf("\n Element 21 \nSymbolic name:- Hf");
	 printf("\n Full form :-Halfnium");
	 printf("\n Atomic number:- 72");
	 printf("\n Atomic mass number:- 198.49");
	 printf("\n---------------------------------");
	 printf("\n Element 22 \nSymbolic name:- Ta");
	 printf("\n Full form :-Tantalum");
	 printf("\n Atomic number:- 73");
	 printf("\n Atomic mass number:- 180.948");
	 printf("\n---------------------------------");
	 system("pause");
	 printf("\n Element 23 \nSymbolic name:- W");
	 printf("\n Full form :-Tungsten");
	 printf("\n Atomic number:- 74");
	 printf("\n Atomic mass number:- 183.84");
	 printf("\n---------------------------------");
	 printf("\n Element 24 \nSymbolic name:- Re");
	 printf("\n Full form :-Rhenium");
	 printf("\n Atomic number:- 75");
	 printf("\n Atomic mass number:- 186.207");
	 printf("\n---------------------------------");
	 printf("\n Element 25 \nSymbolic name:- Os");
	 printf("\n Full form :-Osmium");
	 printf("\n Atomic number:-76");
	 printf("\n Atomic mass number:- 190.23");
	 printf("\n---------------------------------");
	 printf("\n Element 26 \nSymbolic name:- Ir");
	 printf("\n Full form :-Iridium");
	 printf("\n Atomic number:-77");
	 printf("\n Atomic mass number:- 192.217");
	 printf("\n---------------------------------");
	 system("pause");
	 printf("\n Element 27 \nSymbolic name:- Pt");
	 printf("\n Full form :-Platinum");
	 printf("\n Atomic number:- 78");
	 printf("\n Atomic mass number:- 195.085");
	 printf("\n---------------------------------");
	 printf("\n Element 28 \nSymbolic name:- Au");
	 printf("\n Full form :-Gold");
	 printf("\n Atomic number:- 79");
	 printf("\n Atomic mass number:- 196.967");
	 printf("\n---------------------------------");
	 printf("\n Element 29 \nSymbolic name:- Hg");
	 printf("\n Full form :-Mercury");
	 printf("\n Atomic number:- 80");
	 printf("\n Atomic mass number:- 200.592");
	 printf("\n---------------------------------");
	 printf("\n Element 30 \nSymbolic name:- Rf");
	 printf("\n Full form :-Rutherfordium");
	 printf("\n Atomic number:-104");
	 printf("\n Atomic mass number:- [261]");
	 printf("\n---------------------------------");
	 system("pause");
	 printf("\n Element 31 \nSymbolic name:- Db");
	 printf("\n Full form :-Dubnium");
	 printf("\n Atomic number:-105");
	 printf("\n Atomic mass number:- [262]");
	 printf("\n---------------------------------");
	 printf("\n Element 32 \nSymbolic name:- Sg");
	 printf("\n Full form :-Seaburgium");
	 printf("\n Atomic number:-106");
	 printf("\n Atomic mass number:- [266]");
	 printf("\n---------------------------------");
	 printf("\n Element 33 \nSymbolic name:- Bh");
	 printf("\n Full form :-Bohrium");
	 printf("\n Atomic number:- 107");
	 printf("\n Atomic mass number:- [264]");
	 printf("\n---------------------------------");
	 printf("\n Element 34 \nSymbolic name:- Hs");
	 printf("\n Full form :-Hassium");
	 printf("\n Atomic number:- 108");
	 printf("\n Atomic mass number:- [269]");
	 printf("\n---------------------------------");
	 system("pause");
	 printf("\n Element 35 \nSymbolic name:- Mt");
	 printf("\n Full form :-Meitnerium");
	 printf("\n Atomic number:-109");
	 printf("\n Atomic mass number:- [268]");
	 printf("\n---------------------------------");
	 printf("\n Element 36 \nSymbolic name:- Ds");
	 printf("\n Full form :-Darmstatium");
	 printf("\n Atomic number:- 110");
	 printf("\n Atomic mass number:- [269]");
	 printf("\n---------------------------------");
	 printf("\n Element 37 \nSymbolic name:- Rg");
	 printf("\n Full form :-Rongenium");
	 printf("\n Atomic number:- 111");
	 printf("\n Atomic mass number:- [272]");
	 printf("\n---------------------------------");
	 printf("\n Element 38 \nSymbolic name:- Cn");
	 printf("\n Full form :-Copernicum");
	 printf("\n Atomic number:- 112");
	 printf("\n Atomic mass number:- [277]");
	 printf("\n---------------------------------");
	 break;
case 4 : printf("\n The different elements of Basic metals are:" );
	 printf("\n-------------------------------------------------------");
	 printf("\n Element 1 \nSymbolic name:- AI");
	 printf("\n Full form :-Aluminium");
	 printf("\n Atomic number:- 13");
	 printf("\n Atomic mass number:- 22.982");
	 printf("\n---------------------------------");
	 printf("\n Element 2 \nSymbolic name:- Ga");
	 printf("\n Full form :-Gallium");
	 printf("\n Atomic number:-31");
	 printf("\n Atomic mass number:- 69.723");
	 printf("\n---------------------------------");
	 system("pause");
	 printf("\n Element 3 \nSymbolic name:- In");
	 printf("\n Full form :-Indium");
	 printf("\n Atomic number:-49");
	 printf("\n Atomic mass number:- 114.818");
	 printf("\n---------------------------------");
	 printf("\n Element 4 \nSymbolic name:- Sn");
	 printf("\n Full form :-Tin");
	 printf("\n Atomic number:- 50");
	 printf("\n Atomic mass number:- 118.711");
	 printf("\n---------------------------------");
	 printf("\n Element 5 \nSymbolic name:- TI");
	 printf("\n Full form :-Thallium");
	 printf("\n Atomic number:- 81");
	 printf("\n Atomic mass number:- 204.383");
	 printf("\n---------------------------------");
	 printf("\n Element 6 \nSymbolic name:- Pb");
	 printf("\n Full form :-Lead");
	 printf("\n Atomic number:- 82");
	 printf("\n Atomic mass number:- 207.2");
	 printf("\n---------------------------------");
	 system("pause");
	 printf("\n Element 7 \nSymbolic name:- Bi");
	 printf("\n Full form :-Bismuth");
	 printf("\n Atomic number:- 83");
	 printf("\n Atomic mass number:- 208.980");
	 printf("\n---------------------------------");
	 printf("\n Element 8 \nSymbolic name:- Uut");
	 printf("\n Full form :-Ununtrium");
	 printf("\n Atomic number:-113");
	 printf("\n Atomic mass number:- Unknown");
	 printf("\n---------------------------------");
	 printf("\n Element 9 \nSymbolic name:- FI");
	 printf("\n Full form :-Flerovium");
	 printf("\n Atomic number:-114");
	 printf("\n Atomic mass number:- [289]");
	 printf("\n---------------------------------");
	 printf("\n Element 10 \nSymbolic name:- Uup");
	 printf("\n Full form :-Ununpentium");
	 printf("\n Atomic number:- Unknown");
	 printf("\n Atomic mass number:- 65.38");
	 printf("\n---------------------------------");
	 system("pause");
	 printf("\n Element 11 \nSymbolic name:- Lv");
	 printf("\n Full form :-Livermorium");
	 printf("\n Atomic number:- 116");
	 printf("\n Atomic mass number:- [298]");
	 printf("\n---------------------------------");
	 break;
case 5 : printf("\n The different elements of Metalloids are:" );
	 printf("\n-------------------------------------------------------");
	 printf("\n Element 1 \nSymbolic name:- B");
	 printf("\n Full form :-Boron");
	 printf("\n Atomic number:- 5");
	 printf("\n Atomic mass number:- 10.811");
	 printf("\n---------------------------------");
	 printf("\n Element 2 \nSymbolic name:- Si");
	 printf("\n Full form :-Silicon");
	 printf("\n Atomic number:-14");
	 printf("\n Atomic mass number:- 28.086");
	 printf("\n---------------------------------");
	 system("pause");
	 printf("\n Element 3 \nSymbolic name:- Ge");
	 printf("\n Full form :-Germanium");
	 printf("\n Atomic number:-32");
	 printf("\n Atomic mass number:- 72.631");
	 printf("\n---------------------------------");
	 printf("\n Element 4 \nSymbolic name:- As");
	 printf("\n Full form :-Arsenic");
	 printf("\n Atomic number:- 33");
	 printf("\n Atomic mass number:- 74.922");
	 printf("\n---------------------------------");
	 printf("\n Element 5 \nSymbolic name:- Sb");
	 printf("\n Full form :-Antimony");
	 printf("\n Atomic number:- 51");
	 printf("\n Atomic mass number:- 121.760");
	 printf("\n---------------------------------");
	 printf("\n Element 6 \nSymbolic name:- Te");
	 printf("\n Full form :-Tellurium");
	 printf("\n Atomic number:- 52");
	 printf("\n Atomic mass number:- 127.6");
	 printf("\n---------------------------------");
	 system("pause");
	 printf("\n Element 7 \nSymbolic name:- Po");
	 printf("\n Full form :-Polonium");
	 printf("\n Atomic number:- 84");
	 printf("\n Atomic mass number:- [208.982]");
	 printf("\n---------------------------------");
	 break;
case 6 : printf("\n The different elements of Nonmetals are:" );
	 printf("\n-------------------------------------------------------");
	 printf("\n Element 1 \nSymbolic name:- H");
	 printf("\n Full form :-Hydrogen");
	 printf("\n Atomic number:- 1");
	 printf("\n Atomic mass number:- 1.008");
	 printf("\n---------------------------------");
	 printf("\n Element 2 \nSymbolic name:- C");
	 printf("\n Full form :-Carbon");
	 printf("\n Atomic number:-6");
	 printf("\n Atomic mass number:- 12.011");
	 printf("\n---------------------------------");
	 system("pause");
	 printf("\n Element 3 \nSymbolic name:- N");
	 printf("\n Full form :-Nitrogen");
	 printf("\n Atomic number:-7");
	 printf("\n Atomic mass number:- 14.007");
	 printf("\n---------------------------------");
	 printf("\n Element 4 \nSymbolic name:- O");
	 printf("\n Full form :-Oxygen");
	 printf("\n Atomic number:- 8");
	 printf("\n Atomic mass number:- 15.999");
	 printf("\n---------------------------------");
	 printf("\n Element 5 \nSymbolic name:- P");
	 printf("\n Full form :-Phosphorous");
	 printf("\n Atomic number:- 15");
	 printf("\n Atomic mass number:- 30.974");
	 printf("\n---------------------------------");
	 printf("\n Element 6 \nSymbolic name:- S");
	 printf("\n Full form :-Sulphur");
	 printf("\n Atomic number:- 16");
	 printf("\n Atomic mass number:- 32.066");
	 printf("\n---------------------------------");
	 system("pause");
	 printf("\n Element 7 \nSymbolic name:- Se");
	 printf("\n Full form :-Selenium");
	 printf("\n Atomic number:- 34");
	 printf("\n Atomic mass number:- 78.971");
	 printf("\n---------------------------------");
	 break;
case 7 : printf("\n The different elements of Nonmetals are:" );
	 printf("\n-------------------------------------------------------");
	 printf("\n Element 1 \nSymbolic name:- F");
	 printf("\n Full form :-Fluorine");
	 printf("\n Atomic number:- 9");
	 printf("\n Atomic mass number:- 18.978");
	 printf("\n---------------------------------");
	 printf("\n Element 2 \nSymbolic name:- Cl");
	 printf("\n Full form :-Chlorine");
	 printf("\n Atomic number:-17");
	 printf("\n Atomic mass number:- 35.453");
	 printf("\n---------------------------------");
	 system("pause");
	 printf("\n Element 3 \nSymbolic name:- Br");
	 printf("\n Full form :-Bromine");
	 printf("\n Atomic number:-35");
	 printf("\n Atomic mass number:- 79.904");
	 printf("\n---------------------------------");
	 printf("\n Element 4 \nSymbolic name:- I");
	 printf("\n Full form :-Iodine");
	 printf("\n Atomic number:- 53");
	 printf("\n Atomic mass number:- 126.904");
	 printf("\n---------------------------------");
	 printf("\n Element 5 \nSymbolic name:- At");
	 printf("\n Full form :-Astatine");
	 printf("\n Atomic number:- 85");
	 printf("\n Atomic mass number:- 209.987");
	 printf("\n---------------------------------");
	 printf("\n Element 6 \nSymbolic name:- Uus");
	 printf("\n Full form :-Ununseptium");
	 printf("\n Atomic number:- 117");
	 printf("\n Atomic mass number:- Unknown");
	 break;
case 8 : printf("\n The different elements of Noble Gases are:" );
	 printf("\n-------------------------------------------------------");
	 printf("\n Element 1 \nSymbolic name:- He");
	 printf("\n Full form :-Helium");
	 printf("\n Atomic number:- 2");
	 printf("\n Atomic mass number:- 4.003");
	 printf("\n---------------------------------");
	 printf("\n Element 2 \nSymbolic name:- Ne");
	 printf("\n Full form :-Neon");
	 printf("\n Atomic number:- 10");
	 printf("\n Atomic mass number:- 20.180");
	 printf("\n---------------------------------");
	 system("pause");
	 printf("\n Element 3 \nSymbolic name:- Ar");
	 printf("\n Full form :-Argon");
	 printf("\n Atomic number:- 18");
	 printf("\n Atomic mass number:- 39.948");
	 printf("\n---------------------------------");
	 printf("\n Element 4 \nSymbolic name:- Kr");
	 printf("\n Full form :-Krypton");
	 printf("\n Atomic number:- 36");
	 printf("\n Atomic mass number:- 84.798");
	 printf("\n---------------------------------");
	 printf("\n Element 5 \nSymbolic name:- Xe");
	 printf("\n Full form :-Xenon");
	 printf("\n Atomic number:- 54");
	 printf("\n Atomic mass number:- 131.249");
	 printf("\n---------------------------------");
	 printf("\n Element 6 \nSymbolic name:- Rn");
	 printf("\n Full form :-Radon");
	 printf("\n Atomic number:- 86");
	 printf("\n Atomic mass number:- 272.018");
	 printf("\n---------------------------------");
	 system("pause");
	 printf("\n Element 7 \nSymbolic name:- Uuo");
	 printf("\n Full form :-Ununoctium");
	 printf("\n Atomic number:- 118");
	 printf("\n Atomic mass number:- Unknown");
	 printf("\n---------------------------------");
	 break;
case 9 : printf("\n The different elements of Lanthanides are:" );
	 printf("\n-------------------------------------------------------");
	 printf("\n Element 1 \nSymbolic name:- La");
	 printf("\n Full form :-Lanthanum");
	 printf("\n Atomic number:- 57");
	 printf("\n Atomic mass number:- 138.905");
	 printf("\n---------------------------------");
	 printf("\n Element 2 \nSymbolic name:- Ce");
	 printf("\n Full form :-Cerium");
	 printf("\n Atomic number:-58");
	 printf("\n Atomic mass number:- 140.116");
	 printf("\n---------------------------------");
	 system("pause");
	 printf("\n Element 3 \nSymbolic name:- Pr");
	 printf("\n Full form :-Praseodymium");
	 printf("\n Atomic number:-59");
	 printf("\n Atomic mass number:- 140.908");
	 printf("\n---------------------------------");
	 printf("\n Element 4 \nSymbolic name:- Nd");
	 printf("\n Full form :-Neodymium");
	 printf("\n Atomic number:- 60");
	 printf("\n Atomic mass number:- 144.243");
	 printf("\n---------------------------------");
	 printf("\n Element 5 \nSymbolic name:- Pm");
	 printf("\n Full form :-Promethium");
	 printf("\n Atomic number:- 61");
	 printf("\n Atomic mass number:- 144.913");
	 printf("\n---------------------------------");
	 printf("\n Element 6 \nSymbolic name:- Sm");
	 printf("\n Full form :-Samarium");
	 printf("\n Atomic number:- 62");
	 printf("\n Atomic mass number:- 150.36");
	 printf("\n---------------------------------");
	 system("pause");
	 printf("\n Element 7 \nSymbolic name:- Eu");
	 printf("\n Full form :-Europium");
	 printf("\n Atomic number:- 63");
	 printf("\n Atomic mass number:- 151.964");
	 printf("\n---------------------------------");
	 printf("\n Element 8 \nSymbolic name:- Gd");
	 printf("\n Full form :-Gadollnium");
	 printf("\n Atomic number:-64");
	 printf("\n Atomic mass number:- 157.25");
	 printf("\n---------------------------------");
	 printf("\n Element 9 \nSymbolic name:- Tb");
	 printf("\n Full form :-Terbium");
	 printf("\n Atomic number:-65");
	 printf("\n Atomic mass number:- 158.925");
	 printf("\n---------------------------------");
	 printf("\n Element 10 \nSymbolic name:- Dy");
	 printf("\n Full form :-Dysprosium");
	 printf("\n Atomic number:- 66");
	 printf("\n Atomic mass number:- 162.500");
	 printf("\n---------------------------------");
	 system("pause");
	 printf("\n Element 11 \nSymbolic name:- Ho");
	 printf("\n Full form :-Holmium");
	 printf("\n Atomic number:- 67");
	 printf("\n Atomic mass number:- 164.930");
	 printf("\n---------------------------------");
	 printf("\n Element 12 \nSymbolic name:- Er");
	 printf("\n Full form :-Erbium");
	 printf("\n Atomic number:-68");
	 printf("\n Atomic mass number:- 167.259");
	 printf("\n---------------------------------");
	 printf("\n Element 13 \nSymbolic name:- Tm");
	 printf("\n Full form :-Thullium");
	 printf("\n Atomic number:-69");
	 printf("\n Atomic mass number:- 168.934");
	 printf("\n---------------------------------");
	 printf("\n Element 14 \nSymbolic name:- Yb");
	 printf("\n Full form :-Ytterbium");
	 printf("\n Atomic number:- 70");
	 printf("\n Atomic mass number:- 173.055");
	 printf("\n---------------------------------");
	 system("pause");
	 printf("\n Element 15 \nSymbolic name:- Lu");
	 printf("\n Full form :-Lutetium");
	 printf("\n Atomic number:- 71");
	 printf("\n Atomic mass number:- 174.967");
	 printf("\n---------------------------------");
	 break;
case 10 :printf("\n The different elements of Actinides are:" );
	 printf("\n-------------------------------------------------------");
	 printf("\n Element 1 \nSymbolic name:- Ac");
	 printf("\n Full form :-Actinium");
	 printf("\n Atomic number:- 89");
	 printf("\n Atomic mass number:- 227.028");
	 printf("\n---------------------------------");
	 printf("\n Element 2 \nSymbolic name:- Th");
	 printf("\n Full form :-Thorium");
	 printf("\n Atomic number:-90");
	 printf("\n Atomic mass number:- 232.038");
	 printf("\n---------------------------------");
	 system("pause");
	 printf("\n Element 3 \nSymbolic name:- Pa");
	 printf("\n Full form :-Protactinium");
	 printf("\n Atomic number:-91");
	 printf("\n Atomic mass number:- 231.036");
	 printf("\n---------------------------------");
	 printf("\n Element 4 \nSymbolic name:- U");
	 printf("\n Full form :-Uranium");
	 printf("\n Atomic number:- 92");
	 printf("\n Atomic mass number:- 238.029");
	 printf("\n---------------------------------");
	 printf("\n Element 5 \nSymbolic name:- Np");
	 printf("\n Full form :-Neptunium");
	 printf("\n Atomic number:- 93");
	 printf("\n Atomic mass number:- 237.048");
	 printf("\n---------------------------------");
	 printf("\n Element 6 \nSymbolic name:- Pu");
	 printf("\n Full form :-Plotonium");
	 printf("\n Atomic number:- 94");
	 printf("\n Atomic mass number:- 244.064");
	 printf("\n---------------------------------");
	 system("pause");
	 printf("\n Element 7 \nSymbolic name:- Am");
	 printf("\n Full form :-Americium");
	 printf("\n Atomic number:- 95");
	 printf("\n Atomic mass number:- 243.061");
	 printf("\n---------------------------------");
	 printf("\n Element 8 \nSymbolic name:- Cm");
	 printf("\n Full form :-Curium");
	 printf("\n Atomic number:-96");
	 printf("\n Atomic mass number:- 247.070");
	 printf("\n---------------------------------");
	 printf("\n Element 9 \nSymbolic name:- Bk");
	 printf("\n Full form :-Berkelium");
	 printf("\n Atomic number:-97");
	 printf("\n Atomic mass number:- 247.070");
	 printf("\n---------------------------------");
	 printf("\n Element 10 \nSymbolic name:- Cf");
	 printf("\n Full form :-Californium");
	 printf("\n Atomic number:- 98");
	 printf("\n Atomic mass number:- 251.080");
	 printf("\n---------------------------------");
	 system("pause");
	 printf("\n Element 11 \nSymbolic name:- Es");
	 printf("\n Full form :-Einsteinium");
	 printf("\n Atomic number:- 99");
	 printf("\n Atomic mass number:- [254]");
	 printf("\n---------------------------------");
	 printf("\n Element 12 \nSymbolic name:- Fm");
	 printf("\n Full form :-Fermium ");
	 printf("\n Atomic number:-100");
	 printf("\n Atomic mass number:- 257.095");
	 printf("\n---------------------------------");
	 printf("\n Element 13 \nSymbolic name:- Md");
	 printf("\n Full form :-Mendelevium");
	 printf("\n Atomic number:-101");
	 printf("\n Atomic mass number:- 258.1");
	 printf("\n---------------------------------");
	 printf("\n Element 14 \nSymbolic name:- No");
	 printf("\n Full form :-Nobellium");
	 printf("\n Atomic number:- 102");
	 printf("\n Atomic mass number:- 259.101");
	 printf("\n---------------------------------");
	 system("pause");
	 printf("\n Element 15 \nSymbolic name:- Lr");
	 printf("\n Full form :-Lawrencium");
	 printf("\n Atomic number:- 103");
	 printf("\n Atomic mass number:- [262]");
	 printf("\n---------------------------------");
	 break;
default :printf("\n Wrong choice entered");
	  break;


 }
 getch();
 }

